### ISSUE TITLE
UI cosmetic: Text field label is pumping

### ISSUE THREAD

**Issue by MacLemon** [anlumo/KaraokeV2#2]
# Summary:
UI cosmetic: Text field label is pumping

## Steps to Reproduce:
On the „Submit your song request“ dialogue:
- When pressing the die button to get a random suggestion:
- The label for the name pumps back and forth (larger and smaller)

## Expected Results:
UI Items should not move on their own.

## Actual Results:
Cursor and label get scaled for a brief moment.

## Regression:
n/a

## Notes:
Cosmetic

## Version Information:
n/a

**Comment by anlumo** [comment]
Will no longer be an issue with #20
