### ISSUE TITLE
Web UI requires connections to www.gstatic.com

### ISSUE THREAD

**Issue by MacLemon** [anlumo/KaraokeV2#27]
## Describe the bug
UI doesn't render anything when access to www.gstatic.com is not possible or denied by an adblocker.

### Steps to Reproduce
1. Have an adblocker in your browser
2. load the web UI while not having access to www.gstatic.com
3. page stays blank

## Current behavior
Browser requires connections to load
- script from www.gstatic.com
- XHR requests to www.gstatic.com

If these connections are not possible (because connectivity issues of the local network) or blocked by an adblocker, the whole page stays blank.

## Expected behavior
`SHOULD NOT` request anything from 3rd party servers.
`MUST NOT` *depend* on 3rd party requests to render at all.

## Notes
Possible solutions:
- Download these assets at build time and serve locally (ideal, not depending on internet access at runtime, no privacy issues for users)
- Proxy these assets via the server and cache them on the server so no user directly requests these assets (still depends on internet connectivity which may not be a given at all times).

`main.dart.js:458`
        
```        
GET https://www.gstatic.com/flutter-canvaskit/3f3e560236539b7e2702f5ac790b2a4691b32d49/chromium/canvaskit.js net::ERR_BLOCKED_BY_CLIENT
https://www.gstatic.com/flutter-canvaskit/3f3e560236539b7e2702f5ac790b2a4691b32d49/canvaskit.js net::ERR_BLOCKED_BY_CLIENT

main.dart.js:29791 Rejecting promise with error: Exception: Failed to download any of the following CanvasKit URLs: (https://www.gstatic.com/flutter-canvaskit/3f3e560236539b7e2702f5ac790b2a4691b32d49/chromium/canvaskit.js, https://www.gstatic.com/flutter-canvaskit/3f3e560236539b7e2702f5ac790b2a4691b32d49/canvaskit.js)
```

**Comment by anlumo** [comment]
Need to fix canvaskit to link to local

**Comment by MacLemon** [comment]
Perfectly fixed!
