### ISSUE TITLE
Make filters available for library browsing

### ISSUE THREAD

**Issue by MacLemon** [anlumo/KaraokeV2#31]
## Story or task
As a user I want to browse the whole library with the same filters that can be applied to search, when looking for inspiration what to sing.

## Notes
- Need to discuss where we could put those icons.
- Filters should apply globally, so when changed in one place (search) apply the same filters to the library browser as well.

**Comment by anlumo** [comment]
Add toolbar on top for the filter buttons.

**Comment by MacLemon** [comment]
filters nicely.
