### ISSUE TITLE
Music Player cannot be controlled with spacebar, cursor keys

### ISSUE THREAD

**Issue by MacLemon** [anlumo/KaraokeV2#33]
## Story or task
As a user I want to control play/pause in the music player with the space bar.
As a user I want to control 10s fast forward and rewind with the cursor keys.

## Notes
On a laptop/desktop people will likely expect this to work, especially play/pause.
Convenience feature.

**Comment by anlumo** [comment]
* 0: jump to start
* Arrow left: 10s prev
* Arrow right: 10s fwd
* space: play/pause

**Comment by MacLemon** [comment]
Controls work as expected.
