### ISSUE TITLE
[ ] - Add Readme.md

### ISSUE THREAD

**Issue by kaljitism** [anlumo/KaraokeV2#38]
## Tasks
 Add a descriptive Readme, ideally containing- 
- [ ] Introduction 
- [ ] Tech/ Dependencies/ Versions 
- [ ] Setup and Getting Started 
- [ ] Architectural Overview 
- [ ] Usage 
- [ ] Contribution Details 

## Notes - 
would be helpful for random passers by like me to understand what it does and allowing them a upper hand of understanding before they dive into the source.

**Comment by anlumo** [comment]
Thank you for nudging me to finally do this!
