### ISSUE TITLE
Allow multi selection in language filter

### ISSUE THREAD

**Issue by MacLemon** [anlumo/KaraokeV2#5]
# Summary:
Allow multi selection in language filter

## Steps to Reproduce:
Use language filter to reduce library to the songs in languages that a user knows.
User knows multiple languages, but the langauge filter only allows for ALL or a single language.

## Expected Results:
User wants to select the set of languages they speak, and have that stay put for the whole evening.

## Actual Results:
Only filtering by a single language is possible.
Or ALL languages, meaning no filter is applied.

## Regression:
n/a

## Notes:
n/a

## Version Information:
n/a

**Comment by anlumo** [comment]
Needs definition how to handle songs with multiple languages.

**Comment by MacLemon** [comment]
When any of the languages in the `#LANGUAGE` tag of a song matches, it should appear. Since there's neither a convention nor specification on how multiple languages should be ordered in the tag, there's no guaranteed reproducible way to weigh them.

Languages could be listed “in order of appearance”, could also be in “major language is <X>, but chorus is in <Y>”, or “mostly in <X>, but there's also a verse in <Y>”.


Q: Is is reasonably safe to *assume* that the *first* language in the tag is the most important?
I'd say, yes it is.

Expected UI Challenge: Let it go (Disney, Frozen) in 25 languages. :-) 

For example: Same song, available in English or French, or in a mix of both. The language selection *could* affect 2nd order sub-sorting of songs.

- Language filter set to `English` (only)
- User searches for “Supreme” 
1. Robbie Williams: Supreme (`#LANGUAGE English`) 
2. Robbie Williams: Supreme (`#LANGUAGE English, French`) 

Probably not easy to do, and likely not worth doing sub-sorting on that kind of metadata.

**Comment by MacLemon** [comment]
![language filter 62](https://github.com/anlumo/KaraokeV2/assets/90635/85cc3106-4078-4c83-bbb7-cedcb4bcae72)
Multiselect works fine, even for larger sets.
