### ISSUE TITLE
UI: Language filter doesn't indicate filter status detailed enough

### ISSUE THREAD

**Issue by MacLemon** [anlumo/KaraokeV2#6]
# Summary:
UI: Language filter doesn't show if it's applied or set to show ALL

## Steps to Reproduce:
Apply language filter for a language

## Expected Results:
Icon should somehow indicate that it's being applied for the number of picked languages.
For example *one*, or in the context of #5 how many languages are chosen.

For example by applying a number badge that represents the number of selected languages for the filter.

## Actual Results:
Icon stays identical for all states, but only slightly changes in colour. (This colour change was already overseen by a tester.)

HIG:
- Always have two different ways to distinguish items from each other
  - For example: colour `AND` shape

## Regression:
n/a

## Notes:
n/a

## Version Information:
n/a

**Comment by anlumo** [comment]
https://api.flutter.dev/flutter/material/Badge-class.html

**Comment by MacLemon** [comment]
![Image](https://github.com/anlumo/KaraokeV2/assets/90635/73dc6cfe-c31f-4e6d-9af8-83f93e6d7a6e)

Language filter is properly displayed, even for larger sets.
